### ISSUE TITLE
Scala 3.3.0: RefinedTypeOps members not visible outside module containing definition

### ISSUE THREAD

**Issue by ajaychandran** [Iltotore/iron#131]
**Describe the bug**
Scala environment: JVM/Scala.JS/ScalaNative
Scala version: 3.3.0
Iron version: 2.1.0-3-69fb90-SNAPSHOT

**Reproduction steps**
Given the following new type:
```scala
package xxx

import io.github.iltotore.iron.*

opaque type Answer = String :| (StrictEqual["yes"] | StrictEqual["no"])
object Answer extends RefinedTypeOps[Answer]

val a = Answer("yes") // compiles when in same file
```
Moving the last line to a different file results in a compilation error:
```
object Answer in package xxx does not take parameters
``` 
**Expected behavior**
Compilation success.

**Current behavior**
Compilation failure.

**Comment by Iltotore** [comment]
It compiles for me:

refinedtypeops.scala
```scala
import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.all.*

opaque type Answer = String :| (StrictEqual["yes"] | StrictEqual["no"])
object Answer extends RefinedTypeOps[Answer]
```

refinedtest.sc
```scala
//> using scala "3.2.2"
//> using repository "sonatype:snapshots"
//> using lib "io.github.iltotore::iron:2.1.0-3-69fb90-SNAPSHOT"
//> using file "refinedops.scala"

val a = Answer("yes")
println(a)
```

Can you show the code of the second file?

**Comment by Iltotore** [comment]
It seems that in Scala 3.3, imports got a bit stricter. This code works on both 3.2.2 and 3.3.0:

```scala
import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.all.*

opaque type Answer = String :| (StrictEqual["yes"] | StrictEqual["no"])
object Answer extends RefinedTypeOps[Answer]
```

```scala
//> using scala "3.3.0"
//> using repository "sonatype:snapshots"
//> using lib "io.github.iltotore::iron:2.1.0-3-69fb90-SNAPSHOT"
//> using file "refinedops.scala"
//> using file "refinedfile.scala"

//You need to import the associated constraints in Scala 3.3.0
import io.github.iltotore.iron.constraint.all.*

val a = Answer("yes")
println(a)
```

Hope that helps.

However, the error message you got is unclear and is probably a bug from Scala 3.3. Fortunately the workaround is simple.

**Comment by ajaychandran** [comment]
My project consists of multiple modules built using Mill.
The compilation error only occurs when making the call from a different (dependent) module. That is, calls compile when made from a file in the same module.

> //You need to import the associated constraints in Scala 3.3.0
> import io.github.iltotore.iron.constraint.all.*

This did not work.

Will investigate further.

**Comment by Iltotore** [comment]
I will try to test it in two separated modules. Honestly it looks like a bug from Scala 3.3 to me since this "from dependent module" configuration is already tested in 3.2.2 in the test module.

**Comment by ajaychandran** [comment]
> I will try to test it in two separated modules. Honestly it looks like a bug from Scala 3.3 to me since this "from dependent module" configuration is already tested in 3.2.2 in the test module.

Yep, downgrading to 3.2.2 resolved the issue.

**Comment by Iltotore** [comment]
Linked issue: https://github.com/lampepfl/dotty/issues/17984

**Comment by Iltotore** [comment]
A workaround is to use `RefinedTypeOpsImpl` (a bit more boilerplate) instead of `RefinedTypeOps` when using the custom types in another module, until the bug linked above is fixed.

**Comment by Zelenya** [comment]
I'd like to clarify for others and future me (cause it took me sometime to understand the workaround). This works across modules:
```scala
opaque type Answer = String :| (StrictEqual["yes"] | StrictEqual["no"])
// object Answer extends RefinedTypeOps[Answer]
object Answer extends RefinedTypeOpsImpl[String, StrictEqual["yes"] | StrictEqual["no"], Answer]
```
